### ISSUE TITLE
React-router-dom routing (Navbar)

### ISSUE THREAD

**Issue by Tomas-Sedurskas** [JAMT-UCN/react-chat-app#10]
Need to create main pages:
Homepage
Contacts
Create New Group
Add User to Contacts
Settings/Profile
==============
Navbar for all these pages

**Comment by aletrianti** [comment]
Perfect! Do you want to keep working on those (in terms of basic styling) or should I merge your branch into master first?

**Comment by aletrianti** [comment]
Perfect! Do you want to keep working on those (in terms of basic styling) or should I merge your branch into master first?

(Since you are using the same branch for both issues, I'll wait for you to tell me whether you want me to merge the branch or not. But I would say that the other issue is done for now. And yes, I'm on github at this time LOL)
